BEGIN;

INSERT INTO categories (bit_position, slug, display_name, description)
VALUES
  (0, 'ai_slop', 'AI Slop', 'Low-quality, generic, or spammy AI-generated posts and replies.'),
  (1, 'ai_maximalism_evangelists', 'AI Maximalism Evangelists', 'Accounts pushing uncritical hype that AI replaces human creativity or judgment.'),
  (2, 'engagement_farming', 'Engagement Farming', 'Posts designed only to drive likes, reposts, or replies without real substance.'),
  (3, 'low_effort_memes', 'Low Effort Memes', 'Recycled or lazy meme spam that clogs timelines with little originality.'),
  (4, 'crypto_spam', 'Crypto Spam', 'Unsolicited token shilling, airdrop noise, or repetitive crypto promotions.'),
  (5, 'ragebait', 'Ragebait', 'Content crafted mainly to provoke anger or outrage for engagement.'),
  (6, 'porn_bots', 'Porn Bots', 'Automated or spam accounts distributing adult content or links.'),
  (7, 'political_spam', 'Political Spam', 'Repetitive or manipulative political messaging, astroturfing, or bot-like campaigning.'),
  (8, 'reply_bots', 'Reply Bots', 'Automated replies that hijack threads with irrelevant or canned responses.'),
  (9, 'self_promo', 'Self Promo', 'Excessive unsolicited promotion of products, newsletters, or channels.'),
  (10, 'stolen_content', 'Stolen Content', 'Content reposted without credit from creators who own the original work.'),
  (11, 'scams', 'Scams', 'Fraudulent offers, phishing patterns, or obvious scam behavior.'),
  (12, 'health_misinformation', 'Health Misinformation', 'Dangerous or false health claims that could mislead readers.'),
  (13, 'disinfo', 'Disinformation', 'Deliberately false or misleading claims presented as fact.'),
  (14, 'extremist_propaganda', 'Extremist Propaganda', 'Content promoting extremist ideology, recruitment, or violent narratives.'),
  (15, 'hate_speech', 'Hate Speech', 'Harassment or slurs targeting people based on identity or protected traits.'),
  (16, 'doxxing', 'Doxxing', 'Sharing private personal information to harass or endanger someone.'),
  (17, 'gore_shock_media', 'Gore & Shock Media', 'Graphic violence, shock imagery, or gratuitous gore without meaningful context.'),
  (18, 'chain_letter_threads', 'Chain Letter Threads', 'Copy-paste chain posts that pressure others to spread junk across the network.'),
  (19, 'horoscope_spam', 'Horoscope Spam', 'Astrology or horoscope spam used to farm engagement or sell readings.'),
  (20, 'pump_and_dump_traders', 'Pump and Dump Traders', 'Coordinated hype to manipulate asset prices for quick profit.'),
  (21, 'mlm', 'MLM / Pyramid Messaging', 'Multi-level marketing recruitment, downline spam, or pyramid-style pitches.'),
  (22, 'forex_shillers', 'Forex Shillers', 'Aggressive forex or trading course scams and get-rich-quick trading posts.'),
  (23, 'giveaway_bots', 'Giveaway Bots', 'Fake giveaways, prize scams, or bot accounts impersonating brands.'),
  (24, 'pirated_content', 'Pirated Content', 'Links or posts primarily distributing pirated media or warez.'),
  (25, 'follow4follow', 'Follow4Follow Spam', 'Follow-for-follow rings and mutual follow begging that degrades feed quality.'),
  (26, 'nft_clickbait', 'NFT Clickbait', 'NFT hype posts, low-effort PFP grifts, or repetitive NFT promotions.'),
  (27, 'brand_stan_accounts', 'Brand Stan Accounts', 'Accounts that exist mainly to worship or obsessively defend a brand or celebrity.'),
  (28, 'threadboi_fluff', 'Threadboi Fluff', 'Long threads that promise insight but deliver empty motivational filler.'),
  (29, 'quote_tweet_farmers', 'Quote Tweet Farmers', 'Quote-tweeting solely to farm visibility off others without adding value.'),
  (30, 'sob_story_bait', 'Sob Story Bait', 'Emotional manipulation or fabricated hardship stories to drive engagement or donations.'),
  (31, 'fake_expert_gurus', 'Fake Expert Gurus', 'Posing as experts to sell courses, signals, or access with fake credibility.'),
  (32, 'forced_positivity_cult', 'Forced Positivity Cult', 'Toxic positivity that dismisses real harm or shames people for normal feelings.'),
  (33, 'edgelord_trolls', 'Edgelord Trolls', 'Provocateurs who stir drama or offense as their main brand.'),
  (34, 'mass_tagging', 'Mass Tagging', 'Spamming many @mentions or lists to force notifications.'),
  (35, 'lottery_prediction_spam', 'Lottery Prediction Spam', 'Fake winning numbers, prediction scams, or gambling spam.'),
  (36, 'job_listing_scams', 'Job Listing Scams', 'Fake jobs, reshipping scams, or bait-and-switch employment offers.'),
  (37, 'link_shortener_bait', 'Link Shortener Bait', 'Opaque short links used to hide spam, malware, or click fraud.'),
  (38, 'perpetual_preorder_hype', 'Perpetual Preorder Hype', 'Endless preorder or crowdfund hype without shipping real products.')
ON CONFLICT (bit_position) DO NOTHING;

COMMIT;
